spring:
  application:
    name: coffee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: coffee_user
    password: a123456789
  mustache:
    suffix: .html
    enabled: true

mybatis:
  type-aliases-package: com.mjc813.coffee
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  port: 8080


