spring:
  application:
    name: webcrud
  datasource: # mysql 일경우
    url: jdbc:mysql://localhost:3306/webcrud_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8    # 데이터베이스 URL
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC 드라이버 클래스 (MySQL의 경우)
    username: webuser  # 데이터베이스 사용자 이름
    password: a123456789  # 데이터베이스 비밀번호
  mustache:
    servlet:
      cache: false
    suffix: .html

server:
  port: 8080
